name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: labeling
    runs-on: ubuntu-latest
    steps:
      - uses: pullreminders/label-when-approved-action@master
        with:
          APPROVALS: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: approved      
